---
inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: true

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
