---
inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: true
  Exclude:
  - spec/lib/parse_xml_data_spec.rb
  - spec/lib/process_items_spec.rb

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
